feat: implement upsert function
metarhia/metasql pull request #157
Opened 2021-06-23 17:15 UTC by OleksiiKachan

- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md
- [ ] update .d.ts typings

2021-06-23 20:53 UTC, tshemsedinov approved these changes

2021-06-23 20:54 UTC, tshemsedinov commented
Do you need help to add typings?

2021-06-23 21:11 UTC, OleksiiKachan commented
@tshemsedinov I'm pushing types in different branch
noticed that metasql.d.ts has empty class, so I branched and added declarations

2021-06-23 21:16 UTC, OleksiiKachan commented
@tshemsedinov https://github.com/metarhia/metasql/pull/158

2021-06-26 15:05 UTC, OleksiiKachan commented
@tshemsedinov added types

2021-07-03 21:13 UTC, tshemsedinov requested changes

2021-07-03 21:13 UTC, tshemsedinov commented on lib/database.js
> +  }
We can use `buildWhere` here

2021-07-22 13:25 UTC, OleksiiKachan commented
waiting for https://github.com/metarhia/metasql/pull/167

2021-12-19 21:06 UTC, closed without merging