Add Types
metarhia/metasql pull request #158
Opened 2021-06-23 21:16 UTC by OleksiiKachan

- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md
- [x] update .d.ts typings

2021-06-23 21:21 UTC, OleksiiKachan commented
@tshemsedinov please review

2021-06-23 21:35 UTC, OleksiiKachan commented
after this one is merged, gonna merge metarhia:master into my upsert branch and will add upsert function to declarations there

2021-06-23 21:45 UTC, OleksiiKachan commented
https://github.com/metarhia/sql/issues/17

2021-07-03 20:26 UTC, tshemsedinov requested changes

2021-07-03 20:26 UTC, tshemsedinov commented on CHANGELOG.md
> +- Add typing for Database and Query classes
```suggestion
- Add typings for Database and Query classes
```

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  ): Promise<string | number | undefined>;
I'd better define type `ScalarValue` to reuse declaration

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  ) => Promise<Array<string | number | undefined>>;
```suggestion
  ): Promise<Array<string | number | undefined>>;
```

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  ) => Promise<object>;
```suggestion
  ): Promise<object>;
```

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  delete: (table: string, ...conditions: Array<object>) => Promise<QueryResult>;
```suggestion
  delete(table: string, ...conditions: Array<object>): Promise<QueryResult>;
```

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  ) => Promise<QueryResult>;
```suggestion
  ): Promise<QueryResult>;
```

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  close: () => void;
```suggestion
  close(): void;
```

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  update: (
```suggestion
  update(
```

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  dict: (
```suggestion
  dict(
```

2021-07-03 20:26 UTC, tshemsedinov commented on types/metasql.d.ts
> +  col: (
```suggestion
  col(
```

2021-07-04 07:47 UTC, tshemsedinov commented
Landed in https://github.com/metarhia/metasql/commit/cdcf9e15b3413586140dc07fc3d48896f6260c4d

2021-07-04 07:47 UTC, closed without merging